### ISSUE TITLE
final project

### ISSUE THREAD

**Issue by Yvyvibtr** [ducialtit1/OOP---group-20---N03#1]
bt cuối kì là lĩnh vực gì @ducialtit1 

Ý kiến của mình: đang đọc, 15 phút nữa feedback lại

**Comment by ducialtit1** [comment]
ok

**Comment by ducialtit1** [comment]
bạn nghĩ chọn project nào

**Comment by Yvyvibtr** [comment]
xd ứng dụng quản lí nhân sự hoặc là quản lí bán hàng

**Comment by ducialtit1** [comment]
làm cái quản lí bán hàng đi

**Comment by Yvyvibtr** [comment]
lm đến đâu r
